# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'livle_client' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for livle_client
  pod 'FirebaseMessaging'
  pod 'react-native-google-analytics-bridge', :path => '../node_modules/react-native-google-analytics-bridge'

  target 'livle_clientTests' do
    inherit! :search_paths

    # Pods for testing
  end
end
